import React from "react";
import { useState } from "react";
import { Route, Routes } from "react-router-dom";
import SignUpForm from "./components/signup";
import LoginForm from "./components/login";
import Navbar from "./components/navbar";
import Dashboard from "./components/dashboard";

function App() {
  // state for the userID or token generated by the backend.
  // this will be set by the login page
  // and will be passed to the dashboard, so user can have access to dashboard functionalites.

  return (
    <>
      <h1>APP IS THIS</h1>
      {/* <Navbar /> */}
      <Routes>
        <Route exact path='/' element={<h1>H1 hello</h1>} />
        <Route
          path='/signup'
          element={<SignUpForm />}
        />
        <Route path='/login' element={<LoginForm />} />
        <Route path='/dashboard' element={<Dashboard/>} />
      </Routes>
    </>
  );
}

export default App;
